version:  "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672   # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
    volumes:
      - ${HOME}/dev-rabbitmq/data/:/var/lib/rabbitmq
      - ${HOME}/dev-rabbitmq/log/:/var/log/rabbitmq
    restart: always

  db:
    image:  mysql
    restart: always
    ports:
      - 3306:3306 # exposed only for development. Remove in prod
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: my_database
    volumes:
      - $HOME/data/goBlog/mysql:/var/lib/mysql 

  redis-db:
    image:  redis
    restart: always

  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - frontend

  frontend:
    restart: always
    ports:
      - 4000:4000
    build:
      context: ./
      dockerfile: frontend.dockerfile
  
  backend:
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    build:
      context: ./
      dockerfile: backend.dockerfile
    volumes:
      - $HOME/data/gopherblog.com/uploads:/app/uploads


  consumer:
    container_name: consumer
    environment:
      AMQP_SERVER_URL: amqp://guest:guest@rabbitmq
    build:
      context: ./
      dockerfile: consumer.dockerfile
    restart: always
    depends_on:
      - backend
      - rabbitmq



